DROP TABLE IF EXISTS test_audit_logs;
DROP TABLE IF EXISTS test_orders;
DROP TABLE IF EXISTS test_users;
DROP SEQUENCE IF EXISTS test_users_seq;

CREATE SEQUENCE test_users_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE test_users (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(200)
);

CREATE TABLE test_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    amount DECIMAL(10,2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES test_users(id)
);

-- M3: EAGER 관계 검증용 audit log 테이블 (test_orders → EAGER 참조)
CREATE TABLE test_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES test_orders(id)
);
