DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS audit_log;

CREATE TABLE orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    item VARCHAR(200) NOT NULL,
    amount INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    occurred_at TIMESTAMP NOT NULL,
    message VARCHAR(500) NOT NULL
);
