package com.choisk.sfs.orm.support;

import com.choisk.sfs.orm.annotation.SfsColumn;
import com.choisk.sfs.orm.annotation.SfsEntity;
import com.choisk.sfs.orm.annotation.SfsGeneratedValue;
import com.choisk.sfs.orm.annotation.SfsGeneratedValue.GenerationType;
import com.choisk.sfs.orm.annotation.SfsId;
import com.choisk.sfs.tx.jdbc.JdbcTemplate;
import com.choisk.sfs.tx.support.ThreadLocalTsm;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class IdentityGeneratorTest {

    private JdbcDataSource ds;
    private JdbcTemplate jdbc;

    @SfsEntity(name = "id_test")
    static class IdEntity {
        @SfsId
        @SfsGeneratedValue(strategy = GenerationType.IDENTITY)
        Long id;
        @SfsColumn
        String name;
    }

    @BeforeEach
    void setup() {
        ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:idtest;DB_CLOSE_DELAY=-1");
        jdbc = new JdbcTemplate(ds, new ThreadLocalTsm());
        jdbc.update("DROP TABLE IF EXISTS id_test");
        jdbc.update("CREATE TABLE id_test (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100))");
    }

    @Test
    void isPostInsert_returns_true() {
        var gen = new IdentityGenerator(jdbc);
        assertThat(gen.isPostInsert()).isTrue();
    }

    @Test
    void generate_executes_insert_and_returns_generated_key() throws Exception {
        var analyzer = new EntityMetadataAnalyzer();
        var md = analyzer.analyze(IdEntity.class);
        var gen = new IdentityGenerator(jdbc);

        IdEntity e = new IdEntity();
        e.name = "alice";

        Object key = gen.generate(e, md);

        assertThat(key).isNotNull();
        assertThat(((Number) key).longValue()).isEqualTo(1L);
        // DB에 행이 실제로 삽입됐는지 확인 — IDENTITY 전략은 persist == INSERT (학습 정점 ① 깨짐 함정)
        Long count = jdbc.queryForObject("SELECT COUNT(*) FROM id_test WHERE id = ?", Long.class, key);
        assertThat(count).isEqualTo(1L);
    }
}
