package com.choisk.sfs.orm.support;

import com.choisk.sfs.orm.RealEntityManager;
import com.choisk.sfs.orm.SfsEntityManagerFactory;
import com.choisk.sfs.orm.annotation.SfsCascadeType;
import com.choisk.sfs.orm.annotation.SfsColumn;
import com.choisk.sfs.orm.annotation.SfsEntity;
import com.choisk.sfs.orm.annotation.SfsGeneratedValue;
import com.choisk.sfs.orm.annotation.SfsGeneratedValue.GenerationType;
import com.choisk.sfs.orm.annotation.SfsId;
import com.choisk.sfs.orm.annotation.SfsJoinColumn;
import com.choisk.sfs.orm.annotation.SfsManyToOne;
import com.choisk.sfs.orm.annotation.SfsOneToMany;
import com.choisk.sfs.tx.jdbc.JdbcTemplate;
import com.choisk.sfs.tx.support.ThreadLocalTsm;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * RealEntityManager.flush() orphanRemoval — 컬렉션에서 빠진 element가 flush 시 DELETE되는지 검증.
 */
class RealEntityManagerOrphanTest {

    @SfsEntity(name = "orp_parent")
    static class OrpParent {
        @SfsId @SfsGeneratedValue(strategy = GenerationType.IDENTITY) Long id;
        @SfsColumn String name;
        @SfsOneToMany(mappedBy = "parent", cascade = {SfsCascadeType.PERSIST}, orphanRemoval = true)
        List<OrpChild> children = new ArrayList<>();
    }

    @SfsEntity(name = "orp_child")
    static class OrpChild {
        @SfsId @SfsGeneratedValue(strategy = GenerationType.IDENTITY) Long id;
        @SfsManyToOne(fetch = SfsManyToOne.FetchType.LAZY) @SfsJoinColumn(name = "parent_id")
        OrpParent parent;
        @SfsColumn String label;
    }

    private SfsEntityManagerFactory emf;
    private JdbcTemplate jdbc;

    @BeforeEach
    void setup() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:orphan-" + System.nanoTime() + ";DB_CLOSE_DELAY=-1");
        ThreadLocalTsm tsm = new ThreadLocalTsm();
        jdbc = new JdbcTemplate(ds, tsm);
        jdbc.update("CREATE TABLE orp_parent (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(50))");
        jdbc.update("CREATE TABLE orp_child (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, parent_id BIGINT, label VARCHAR(50))");
        // 데이터: parent 1 + child 2
        jdbc.update("INSERT INTO orp_parent (id, name) VALUES (1, 'p1')");
        jdbc.update("INSERT INTO orp_child (id, parent_id, label) VALUES (10, 1, 'c1')");
        jdbc.update("INSERT INTO orp_child (id, parent_id, label) VALUES (11, 1, 'c2')");
        emf = SfsEntityManagerFactory.builder()
                .dataSource(ds).transactionSynchronizationManager(tsm)
                .addEntityClass(OrpParent.class)
                .addEntityClass(OrpChild.class)
                .build();
    }

    @Test
    void 컬렉션에서_remove한_child가_flush_시_DELETE된다() {
        RealEntityManager em = (RealEntityManager) emf.createEntityManager();
        OrpParent p = em.find(OrpParent.class, 1L);

        OrpChild first = p.children.get(0);   // 초기화 → storedSnapshot = [c1, c2]
        p.children.remove(first);             // delegate = [c2]

        em.flush();

        Long remaining = jdbc.queryForObject("SELECT COUNT(*) FROM orp_child", Long.class);
        assertThat(remaining).isEqualTo(1L);   // orphan(c1) 삭제, c2 남음
    }

    @Test
    void 미초기화_컬렉션은_orphan_검사_skip() {
        RealEntityManager em = (RealEntityManager) emf.createEntityManager();
        em.find(OrpParent.class, 1L);   // children 미초기화(접근 안 함)

        em.flush();   // orphan 단계가 미초기화 컬렉션을 건너뛰어 DELETE 0

        Long remaining = jdbc.queryForObject("SELECT COUNT(*) FROM orp_child", Long.class);
        assertThat(remaining).isEqualTo(2L);
    }
}
