package com.choisk.sfs.orm.support;

import com.choisk.sfs.orm.RealEntityManager;
import com.choisk.sfs.orm.SfsEntityManagerFactory;
import com.choisk.sfs.orm.annotation.SfsColumn;
import com.choisk.sfs.orm.annotation.SfsEntity;
import com.choisk.sfs.orm.annotation.SfsGeneratedValue;
import com.choisk.sfs.orm.annotation.SfsGeneratedValue.GenerationType;
import com.choisk.sfs.orm.annotation.SfsId;
import com.choisk.sfs.tx.jdbc.JdbcTemplate;
import com.choisk.sfs.tx.support.ThreadLocalTsm;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * RealEntityManager.persist() — SEQUENCE / IDENTITY 분기 검증.
 *
 * 학습 정점 ① 깨짐 함정 박제:
 * - SEQUENCE: persist() 직후 entity.id는 시퀀스 값으로 채워지지만 DB row는 0건.
 *   1차 캐시 등재 + snapshot 캡처 + actionQueue InsertAction 등록 3가지 완료.
 * - IDENTITY: persist() == 즉시 INSERT. generated key를 entity.id에 주입.
 *   actionQueue에는 등재 안 됨 (flush 시 중복 INSERT 방지).
 */
class RealEntityManagerPersistTest {

    @SfsEntity(name = "persist_seq_test")
    static class SeqUser {
        @SfsId
        @SfsGeneratedValue(strategy = GenerationType.SEQUENCE, sequenceName = "persist_seq")
        Long id;
        @SfsColumn
        String name;
    }

    @SfsEntity(name = "persist_id_test")
    static class IdOrder {
        @SfsId
        @SfsGeneratedValue(strategy = GenerationType.IDENTITY)
        Long id;
        @SfsColumn
        String status;
    }

    private JdbcDataSource ds;
    private ThreadLocalTsm tsm;
    // SeqUser + IdOrder 모두 등록 — 단일 emf로 SEQUENCE/IDENTITY 테스트 공유
    private SfsEntityManagerFactory emf;
    private JdbcTemplate jdbc;

    @BeforeEach
    void setup() {
        ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:rempersist;DB_CLOSE_DELAY=-1");
        tsm = new ThreadLocalTsm();
        jdbc = new JdbcTemplate(ds, tsm);
        // SEQUENCE persist_seq_test 테이블 초기화
        jdbc.update("DROP TABLE IF EXISTS persist_seq_test");
        jdbc.update("DROP SEQUENCE IF EXISTS persist_seq");
        jdbc.update("CREATE SEQUENCE persist_seq START WITH 1");
        jdbc.update("CREATE TABLE persist_seq_test (id BIGINT PRIMARY KEY, name VARCHAR(100))");
        // IDENTITY persist_id_test 테이블 초기화 (테스트 격리)
        jdbc.update("DROP TABLE IF EXISTS persist_id_test");
        jdbc.update("CREATE TABLE persist_id_test (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, status VARCHAR(50))");
        // SeqUser + IdOrder 모두 등록 — PER_METHOD 라이프사이클이므로 테스트 격리에 영향 없음
        emf = SfsEntityManagerFactory.builder()
                .dataSource(ds)
                .transactionSynchronizationManager(tsm)
                .addEntityClass(SeqUser.class)
                .addEntityClass(IdOrder.class)
                .build();
    }

    @Test
    void persist_with_SEQUENCE_strategy_assigns_id_but_does_not_insert() {
        RealEntityManager em = (RealEntityManager) emf.createEntityManager();
        SeqUser u = new SeqUser();
        u.name = "alice";

        em.persist(u);

        // 검증 1: SEQUENCE 미리 받아 id 세팅
        assertThat(u.id).isEqualTo(1L);
        // 검증 2: DB에는 아직 INSERT 안 됨 (학습 정점 ① write-behind)
        Long count = jdbc.queryForObject("SELECT COUNT(*) FROM persist_seq_test", Long.class);
        assertThat(count).isEqualTo(0L);
        // 검증 3: 1차 캐시에 등재
        assertThat(em.context().contains(new EntityKey(SeqUser.class, 1L))).isTrue();
        // 검증 4: actionQueue에 InsertAction 1건
        assertThat(em.context().actionQueue()).hasSize(1);
        assertThat(em.context().actionQueue().get(0)).isInstanceOf(InsertAction.class);
    }

    /**
     * 학습 정점 ① 깨짐 함정 박제 — IDENTITY 전략 즉시 INSERT.
     *
     * IDENTITY 전략은 persist() 호출 순간 DB INSERT가 실행된다.
     * generated key가 entity.id에 주입되고, actionQueue에는 등재하지 않는다.
     * flush 시 actionQueue를 재실행하면 중복 INSERT → UNIQUE 위반이 발생하기 때문이다.
     */
    @Test
    void persist_with_IDENTITY_strategy_immediately_inserts_and_assigns_id() {
        // SeqUser와 동일한 emf 재사용 — @BeforeEach에서 IdOrder.class도 등록됨
        RealEntityManager em = (RealEntityManager) emf.createEntityManager();

        IdOrder o = new IdOrder();
        o.status = "PENDING";
        em.persist(o);

        // 검증 1: generated key가 entity.id에 주입
        assertThat(o.id).isEqualTo(1L);
        // 검증 2: DB에 즉시 INSERT (학습 정점 ① — write-behind 우회)
        Long count = jdbc.queryForObject("SELECT COUNT(*) FROM persist_id_test", Long.class);
        assertThat(count).isEqualTo(1L);
        // 검증 3: actionQueue에는 등재 안 됨 (flush 시 중복 INSERT 방지)
        assertThat(em.context().actionQueue()).isEmpty();
        // 검증 4: 1차 캐시에는 등재 (find() cache hit 보장의 전제 조건)
        assertThat(em.context().contains(new EntityKey(IdOrder.class, 1L))).isTrue();
    }
}
